version = 1

test_patterns = ["**/*Test.java"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "test-coverage"
enabled = true
ignore_merge_commits = false

  [analyzers.test-coverage]
  minimum_coverage = 70