name: DeepSource Analysis

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      - name: Run tests with coverage
        run: mvn clean test jacoco:report

      - name: Install DeepSource CLI
        if: github.event_name == 'push'
        run: curl https://deepsource.com/cli | sh

      - name: Report coverage to DeepSource
        if: github.event_name == 'push'
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          ./bin/deepsource report --analyzer test-coverage --key java --value-file ./git-repository-reader-engine/target/site/jacoco/jacoco.xml