name: CI Pipeline with DeepSource

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Upload Test Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-classes/TEST-*.xml

      - name: Install DeepSource CLI v0.8.6
        run: |
          curl -fsSL https://github.com/DeepSourceCorp/cli/releases/download/v0.8.6/deepsource_0.8.6_linux_x86_64.tar.gz | tar -xzv -C /usr/local/bin

      - name: Run DeepSource Analysis
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: deepsource issues